CREATE TABLE Steps (ID INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(255), description varchar(255), step_desc text);
CREATE TABLE Flows (ID INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(255), description varchar(255), steps varchar(255));
CREATE TABLE Pipelines (ID INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(255), description varchar(255), flows varchar(255));
CREATE TABLE Builds (ID INTEGER PRIMARY KEY AUTOINCREMENT, JOB_ID INTEGER, TASK_ID INTEGER, StartTime TIMESTAMP, EndTime TIMESTAMP, FOREIGN KEY (JOB_ID) REFERENCES Jobs(ID), FOREIGN KEY (TASK_ID) REFERENCES Tasks(ID));
